language: java

jdk:
  - oraclejdk8
      
install: true
script:
  - mvn clean package

after_success:
  - mvn com.blackducksoftware.integration:hub-maven-plugin:2.0.2:build-bom -Dhub.output.directory=. -Dhub.deploy.bdio=false
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./*_bdio.jsonld  